# environment.yml
name: freebayes-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - nextflow
  - freebayes
  - samtools
  - bcftools
  - tabix
  - htslib
  - bedtools